package model;
// Generated Nov 18, 2025 10:48:16 AM by Hibernate Tools 4.3.1

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "mahasiswa")


/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name = "id")
    private Integer id;
    
    @Column(name = "npm")    
    private String npm;
    
    @Column(name = "nama")
    private String nama;
    
    @Column(name = "jurusan")
    private String jurusan;

    public Mahasiswa() {
    }

    public Mahasiswa(String npm, String nama, String jurusan) {
       this.npm = npm;
       this.nama = nama;
       this.jurusan = jurusan;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNpm() {
        return this.npm;
    }
    
    public void setNpm(String npm) {
        this.npm = npm;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getJurusan() {
        return this.jurusan;
    }
    
    public void setJurusan(String jurusan) {
        this.jurusan = jurusan;
    }
    
    @Override
    public String toString(){
        return "Mahasiswa{" +
                "id=" + id +
                ", npm=" + npm + '\''+
                ", nama=" + nama + '\''+
                ", jurusan=" + jurusan + '\''+
                "}";
    }




}


